<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iDM_TD3" nsURI="http://www.example.org/iDM_TD3" nsPrefix="iDM_TD3">
  <eClassifiers xsi:type="ecore:EClass" name="Hotels">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NomHotel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chambre" lowerBound="1"
        upperBound="-1" eType="#//Chambre" eOpposite="#//Chambre/hotel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a_responsable" lowerBound="1"
        eType="#//Responsable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chambre">
    <eOperations name="CalculPrixLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="num_chambre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="num_etage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hotel" lowerBound="1" eType="#//Hotels"
        eOpposite="#//Hotels/chambre"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a_prestations" lowerBound="1"
        upperBound="-1" eType="#//Prestation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="est_loué" eType="#//Hote"
        eOpposite="#//Hote/loue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a_salle_de_bain" eType="#//Salle_de_bain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Responsable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom_responsable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prestation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Prix_Prestation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hote">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loue" lowerBound="1" upperBound="-1"
        eType="#//Chambre" eOpposite="#//Chambre/est_loué"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NomHote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Salle_de_bain"/>
</ecore:EPackage>
